name: creativa
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  shimmer: ^1.1.1
  font_awesome_flutter: ^8.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - images/


fonts:
  - family: Helvetica Neu
    fonts:
      - asset: fonts/HelveticaNeue.ttf
      - asset: fonts/HelveticaNeueMedium.ttf
      - asset: fonts/HelveticaNeuBold.ttf
        style: normal

